name: build cli

on:
  pull_request:
    paths:
      - 'cli/**'
  release:
    types:
      - published

jobs:
  build_packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: build
        run: |
          cd cli
          yarn && yarn build
          npm install -g pkg
          pkg package.json

      - uses: actions/upload-artifact@v2
        with:
          name: cli
          path: cli/release
